### ISSUE TITLE
RecentGames->PlayerGameStats.rating is always 0

### ISSUE THREAD

**Issue by kappa09** [encratite/LibOfLegends#10]
It seems like no matter what ranked soloqueue game and at whichever rating, the library is always saying that the game's rating for the player is 0. So basically you can not view the resulting elo change or the new elo of a player from a game.

Has this been broken for a while or has it ever worked? Did riot change something? Is there a fix to this?

**Comment by encratite** [comment]
It is not the library that is at fault, this is Riot removing data they were "leaking". It is a result of the changes in the server codebase in the Lulu patch.
