### ISSUE TITLE
Question..

### ISSUE THREAD

**Issue by blurfx** [encratite/LibOfLegends#15]
how can i get client version from riot?

**Comment by encratite** [comment]
Uh, that's a tricky one. From what I've gathered you actually need to download the patches and analyse the contents they send you. No fun. You don't really need this to connect, though. You can just like send 1.73.anystring and if that works you can try 1.74.anystring and so on. If you don't care about being detected if they ever decide to do so, you can use this incremental version bruteforcing. It works pretty well.
