### ISSUE TITLE
Finding internal method names

### ISSUE THREAD

**Issue by Tisq** [encratite/LibOfLegends#17]
I was just wondering how you find internal method names for the rpc calls? With the recent changes in season 3, I think there are a few new or changed method names.

**Comment by encratite** [comment]
Optimally you have a TLS MITM proxy between your Adobe AIR client and the LoL servers. This proxy has to be attached to an RTMP/AMFx decoder so you can get decoded dumps of everything the client does. This way you can see all the API calls used and what types the arguments are and such. The setup I use for this involves generating self-signed certificates with OpenSSL, modifying the Windows /etc/hosts file to redirect LoL hosts to 127.0.0.1 and using https://github.com/epicvrvs/TransportLayerInsecurity for the MITM. This is crude, though.

Talk to me here to find out more about this stuff: http://riot.cont.ro.lt/#chat
