### ISSUE TITLE
When compiling, no reference to Proxy

### ISSUE THREAD

**Issue by ramvi** [encratite/LibOfLegends#20]
I know you're not responsible for others to be able to compile your open source code or anything, but if you could take the time to help me, I would be more than thankful!
I have both dependencies compiled and added to the Reference Path: NilSharp and FluorineFXMods.

In both AuthServices and ProxyProfile it's unable to find the reference to Proxy: "The type or namespace name 'Proxy' could not be found". So I've build and added Starksoft.Net.Proxy but still no luck.

This looks like a good project and I would love to contribute, if I get it compiling. Thanks again.

**Comment by ramvi** [comment]
Nevermind, I found that I needed the rtmp_app_layer_mods branch of FluorineFXMods!

**Comment by encratite** [comment]
Oh, yes, indeed, that is a quirk the original author insisted on. He wanted to keep the modifications in a separate branch so we could keep on pulling the main stream into the master branch. We never made use of this, really.

As for great project... well, it's a bit dated now and I'm still upset by several really inefficient things. I haven't updated it properly for season 3. Required many fundamental database modifications.
