### ISSUE TITLE
Since the Lulu patch, PlayerGameStats.rating is always 0.

### ISSUE THREAD

**Issue by akratic** [encratite/LibOfLegends#4]
Since the Lulu patch, PlayerGameStats.rating is always 0, along with teamRating, eloChange, etc.  This makes it impossible to view your normal ELO.

**Comment by encratite** [comment]
Yes, I was committing the patch for the example application just as you wrote that. This is most unfortunate. You might still be able to tell your own normal Elo by sniffing Air data after finishing a game. This would require MITM or (what we used) Air TLS I/O logging.

**Comment by jpmassena** [comment]
Hi there,

about the "Air TLS I/O logging", are you talking about some custom tool or you used a third party one?

**Comment by encratite** [comment]
I used this https://github.com/epicvrvs/LeagueOfInjection in combination with https://github.com/epicvrvs/syringe

Most people just used an MITM approach instead, which is considerably simpler. I believe https://github.com/high6/LoLNotes is one of those.
