### ISSUE TITLE
403 Forbidden on login

### ISSUE THREAD

**Issue by jroweboy** [encratite/LibOfLegends#6]
I tried to use my smurf account to login simultaneously while having the LoL client open my main account when I got a 403 error. I was thinking that the it might have had something to do with the LoL client already being signed in, making this a know error, but if you didn't know about this I figured that I was going to report it anyway. 

If you need some more information, I am a programmer also and would be glad to provide whatever is needed.

**Comment by encratite** [comment]
I'm not sure I ever tried this before but I'm not surprised by the result. Usually I only get 403s when I mess up the password.

**Comment by jroweboy** [comment]
Ah... maybe I typed it in wrong. :O I'll try it again and report back then!

**Comment by jroweboy** [comment]
Yep. I'm just an idiot and typed in the information incorrectly. :)
